steps:
  prettier_check:
    image: jauderho/prettier:3.8.4-alpine
    commands:
      - prettier -c .
    when:
      - event: pull_request

  bash_fmt:
    image: alpine:3
    commands:
      - apk add shfmt
      - shfmt -i 2 -d */**.bash
      - shfmt -i 2 -d */**.sh
    when:
      - event: pull_request
